# Generated by Django 3.1 on 2020-08-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector', models.CharField(max_length=25)),
                ('YrChange', models.CharField(max_length=25)),
                ('DayChange', models.CharField(max_length=25)),
            ],
        ),
    ]
