# Generated by Django 3.1 on 2020-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpow_app', '0002_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Ticker', models.CharField(max_length=5)),
                ('Senator', models.TextField()),
                ('PurchaseType', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
