# Generated by Django 3.1 on 2020-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpow_app', '0003_auto_20200826_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='insider',
            name='Amount',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
