# Generated by Django 3.1 on 2020-08-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpow_app', '0005_compensation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensation',
            name='id',
        ),
        migrations.AlterField(
            model_name='compensation',
            name='Ticker',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
